### ISSUE TITLE
start program with api panic

### ISSUE THREAD

**Issue by GitProBo** [codeskyblue/gosuv#20]
```
#tail -f gosuv.log 
2017/02/08 16:08:18 [INFO][github.com/codeskyblue/gosuv] fsm.go:228: [dbplus10.2.117.14:3309] use dir: /root
2017/02/08 16:08:27 [INFO][github.com/codeskyblue/gosuv] web.go:222: stop before delete program: dbplus10.2.117.14:3309
2017/02/08 16:08:27 [INFO][github.com/codeskyblue/gosuv] fsm.go:314: recv stop command
2017/02/08 16:08:27 [INFO][github.com/codeskyblue/gosuv] fsm.go:261: program(dbplus10.2.117.14:3309) quit normally
2017/02/08 16:08:30 [WARN][github.com/codeskyblue/gosuv] broadcast.go:79: broadcase write error: 1486541194877299479, GoTimeoutFunc
2017/02/08 16:08:37 [INFO][github.com/codeskyblue/gosuv] web.go:512: dbplus10.2.117.14:3309
2017/02/08 16:08:42 [INFO][github.com/codeskyblue/gosuv] fsm.go:288: start cmd(dbplus10.2.117.14:3309): ./metric -i 10.2.117.14:3309 -u maxwell -p 75JGIsP5IM9UUWxr -e 10.2.104.133:9200
2017/02/08 16:08:42 [INFO][github.com/codeskyblue/gosuv] fsm.go:228: [dbplus10.2.117.14:3309] use dir: /root
2017/02/08 16:09:15 [INFO][github.com/codeskyblue/gosuv] web.go:512: dbplus10.2.117.14:3309
2017/02/08 16:11:23 [INFO][github.com/codeskyblue/gosuv] web.go:498: read: -1 websocket: close 1001 
2017/02/08 16:13:17 http: panic serving 172.18.25.90:60055: html/template: cannot redefine "index" after it has executed
goroutine 696 [running]:
net/http.(*conn).serve.func1(0xc42035e180)
        /home/travis/.gimme/versions/go1.7.linux.amd64/src/net/http/server.go:1491 +0x12a
panic(0x7cd260, 0xc420602740)
        /home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:458 +0x243
html/template.Must(0x0, 0xa21fa0, 0xc420602740, 0x0)
        /home/travis/.gimme/versions/go1.7.linux.amd64/src/html/template/template.go:340 +0x66
main.parseTemplate(0x841b48, 0x7, 0xc42036c000, 0x1362)
        /home/travis/gopath/src/github.com/codeskyblue/gosuv/res_bindata.go:25 +0x157
main.executeTemplate(0xa22d60, 0xc4207305b0, 0x841b48, 0x7, 0x7d4f40, 0xc4205e8c90)
        /home/travis/gopath/src/github.com/codeskyblue/gosuv/res_bindata.go:39 +0x1a3
main.(*Supervisor).renderHTML(0xc42001ccd0, 0xa27260, 0xc4207305b0, 0x841b48, 0x7, 0x7d4f40, 0xc4205e8c90)
        /home/travis/gopath/src/github.com/codeskyblue/gosuv/web.go:245 +0x13f
main.(*Supervisor).hSetting(0xc42001ccd0, 0xa27260, 0xc4207305b0, 0xc4208524b0)
        /home/travis/gopath/src/github.com/codeskyblue/gosuv/web.go:267 +0x154
main.(*Supervisor).(main.hSetting)-fm(0xa27260, 0xc4207305b0, 0xc4208524b0)
        /home/travis/gopath/src/github.com/codeskyblue/gosuv/web.go:625 +0x48
net/http.HandlerFunc.ServeHTTP(0xc42034e0b0, 0xa27260, 0xc4207305b0, 0xc4208524b0)
        /home/travis/.gimme/versions/go1.7.linux.amd64/src/net/http/server.go:1726 +0x44
github.com/codeskyblue/gosuv/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201ae460, 0xa27260, 0xc4207305b0, 0xc4208524b0)
        /home/travis/gopath/src/github.com/codeskyblue/gosuv/vendor/github.com/gorilla/mux/mux.go:100 +0x255
net/http.(*ServeMux).ServeHTTP(0xb5f2a0, 0xa27260, 0xc4207305b0, 0xc4208524b0)
        /home/travis/.gimme/versions/go1.7.linux.amd64/src/net/http/server.go:2022 +0x7f
net/http.serverHandler.ServeHTTP(0xc42008b380, 0xa27260, 0xc4207305b0, 0xc4208524b0)
        /home/travis/.gimme/versions/go1.7.linux.amd64/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc42035e180, 0xa27ba0, 0xc4203cb2c0)
        /home/travis/.gimme/versions/go1.7.linux.amd64/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
        /home/travis/.gimme/versions/go1.7.linux.amd64/src/net/http/server.go:2293 +0x44d
2017/02/08 16:16:03 [INFO][github.com/codeskyblue/gosuv] web.go:498: read: -1 websocket: close 1001 
```

**Comment by codeskyblue** [comment]
Have you succeed started?

**Comment by GitProBo** [comment]
failed to start
2017/02/08 16:11:23 [INFO][github.com/codeskyblue/gosuv] web.go:498: read: -1 websocket: close 1001 
websocket is closed when error caused, I think web.go doesnt work at the moment

**Comment by codeskyblue** [comment]
have you see this part? https://github.com/codeskyblue/gosuv#installation

**Comment by GitProBo** [comment]
yes？

**Comment by codeskyblue** [comment]
Can reproduce this issue, closed for now.
